### ISSUE TITLE
Error while doing mvn clean install

### ISSUE THREAD

**Issue by tarunsas** [trecloux/yeoman-maven-plugin#26]
I am using this plugin for a couple of months, i see this error 

[ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.4:build (default) on project spoofer-yo: Error during : cmd /c grunt build --no-color: Process exited with an error: 6 (Exit value: 6) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.4:build (default) on project-yo: Error during : cmd /c grunt build --no-color
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during : cmd /c grunt build --no-color
        at com.github.trecloux.yeoman.YeomanMojo.executeCommand(YeomanMojo.java:127)
        at com.github.trecloux.yeoman.YeomanMojo.logAndExecuteCommand(YeomanMojo.java:108)
        at com.github.trecloux.yeoman.YeomanMojo.build(YeomanMojo.java:97)
        at com.github.trecloux.yeoman.YeomanMojo.execute(YeomanMojo.java:68)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 6 (Exit value: 6)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
        at com.github.trecloux.yeoman.YeomanMojo.executeCommand(YeomanMojo.java:125)
        ... 24 more
[ERROR]

But when i do grunt build , i dont see any error.

-yo>grunt build --no-color
Running "clean:dist" (clean) task
>> 19 paths cleaned.

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "useminPrepare:html" (useminPrepare) task
Configuration changed for concat, uglify, cssmin

Running "concurrent:dist" (concurrent) task

Running "svgmin:dist" (svgmin) task
Total saved: 0 B

Done, without errors.

Execution Time (2015-11-13 20:41:59 UTC)
loading tasks         355ms  █████████████████████ 52%
loading grunt-svgmin  216ms  █████████████ 31%
svgmin:dist           116ms  ███████ 17%
Total 687ms

Running "imagemin:dist" (imagemin) task
Minified 1 image (saved 5 kB)

Done, without errors.

Execution Time (2015-11-13 20:41:59 UTC)
loading tasks                   349ms  ██████ 18%
loading grunt-contrib-imagemin   1.3s  ████████████████████ 66%
imagemin:dist                   306ms  █████ 16%
Total 1.9s

Running "compass:dist" (compass) task
directory .tmp/styles
        write .tmp/styles/main.css (1.202s)

Done, without errors.

Execution Time (2015-11-13 20:41:59 UTC)
loading tasks                  354ms  ███ 10%
loading grunt-contrib-compass   57ms  █ 2%
compass:dist                    3.3s  ████████████████████████████ 89%
Total 3.7s

Running "postcss:server" (postcss) task
>> 1 processed stylesheet created.

Running "postcss:dist" (postcss) task
>> 1 processed stylesheet created.

Running "ngtemplates:dist" (ngtemplates) task
File .tmp/templateCache.js created.
Added .tmp/templateCache.js to 

Running "concat:generated" (concat) task
File .tmp\concat\scripts\vendor.js created.
File .tmp\concat\scripts\scripts.js created.

Running "ngAnnotate:dist" (ngAnnotate) task
>> 2 files successfully generated.

Running "copy:dist" (copy) task
Copied 9 files

Running "cdnify:dist" (cdnify) task
Going through dist/404.html, dist/index.html to update script refs
? bower_components/angular/angular.js changed to //ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.2/angular.min.js
? bower_components/angular/angular.js changed to //ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.2/angular.min.js

Running "cssmin:generated" (cssmin) task
>> 2 files created. 314.96 kB → 116.11 kB

Running "uglify:generated" (uglify) task
>> 2 files created.

Running "filerev:dist" (filerev) task
Revved 5 files

Running "usemin:html" (usemin) task
Replaced 2 references to assets

Running "usemin:css" (usemin) task
Replaced 2 references to assets

Running "usemin:js" (usemin) task
Replaced 2 references to assets

Running "htmlmin:dist" (htmlmin) task
Minified 2 files

Done, without errors.

Execution Time (2015-11-13 20:41:56 UTC)
loading tasks             749ms  ███████████████ 2%
concurrent:dist            5.6s  ██████████████████████████████████████████████████████████████████████████████████████████████████████████████ 15%
postcss:server            494ms  ██████████ 1%
ngAnnotate:dist           848ms  █████████████████ 2%
loading grunt-google-cdn   1.3s  █████████████████████████ 3%
cdnify:dist               22.7s  ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
cssmin:generated          394ms  ████████ 1%
uglify:generated           4.8s  ███████████████████████████████████████████████████████████████████████████████████████████████ 13%
Total 38.5s

I dont see any errors.

**Comment by tarunsas** [comment]
Both grunt and grunt server works without any issues. only when i invoke maven plugin it errors out. 
What could be the reason?

Any help...

**Comment by trecloux** [comment]
Could you please check grunt return code after a manual execution ?

```
echo %errorlevel%
```

**Comment by tarunsas** [comment]
Thanks Thomas

Where do we add this ? Also when I do --force in the configuration it is
picking up only one image from images/ directory randomly . But the build
is successful

The same plugin worked before any changes except Windows update

Can the update cause this ?

**Comment by tarunsas** [comment]
[INFO] --------------------------------------
[INFO]          GRUNT BUILD --NO-COLOR
[INFO] --------------------------------------
Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "jsbeautifier:files" (jsbeautifier) task
Beautified 6 files, changed 0 files...OK

Running "prettify:html" (prettify) task

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "useminPrepare:html" (useminPrepare) task
Configuration changed for concat, uglify, cssmin

Running "concurrent:dist" (concurrent) task
    
Running "copy:styles" (copy) task
Copied 2 files

Done, without errors.


Execution Time (2015-11-14 15:44:22 UTC)
loading tasks  13ms  █████████████████ 35%
copy:styles    24ms  ███████████████████████████████ 65%
Total 37ms
    Warning: Running "imagemin:dist" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined


Execution Time (2015-11-14 15:44:22 UTC)
loading tasks   12ms  ██ 3%
imagemin:dist  354ms  ██████████████████████████████████████████████ 96%
Total 367ms Use --force to continue.
    
    Aborted due to warnings.


Execution Time (2015-11-14 15:44:14 UTC)
jsbeautifier:files  119ms  █ 1%
wiredep:app         346ms  ██ 4%
concurrent:dist      8.1s  ████████████████████████████████████████ 94%
Total 8.6s

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:29 min
[INFO] Finished at: 2015-11-14T09:44:23-06:00
[INFO] Final Memory: 9M/180M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.4:build (default) on projectspoofer-yo: Error during : cmd /c grunt build --no-color: Process exited with an error: 6 (Exit value: 6) -> [Help 1]

**Comment by tarunsas** [comment]
It is due to imagemin version. After i update, it is working fine.

Thanks
sriram

**Comment by trecloux** [comment]
Good to hear :-)

**Comment by aillon** [comment]
Hi ......without any apparent reason, suddenly I am having this exact issue on my windows machine.  I've updated imagemin but the same error persists.  Can someone tell me what to check or upgrade to get rid of this problem?  Thank you

**Comment by vinnysharma** [comment]
I too have this error out of nowhere. It had been working fine, but now I see the error below when I run this command: mvn clean install -Dmaven.test.skip=true.  

Console error log is below:

bower angular#~1.x                                 ENOTEMPTY ENOTEMPTY: directory not empty, rename '/var/folders/mt/1_87y8217vj73xs5fbp0hkmh0000gp/T/vinny/bower/angular-5031-q7wfAb' -> '/Users/vinny/.cache/bower/packages/060a9fe0e60a0d3d6c9ed350cde03e61/1.5.6-build.4794%2Bsha.f1f892d'

Stack trace:
Error: ENOTEMPTY: directory not empty, rename '/var/folders/mt/1_87y8217vj73xs5fbp0hkmh0000gp/T/vinny/bower/angular-5031-q7wfAb' -> '/Users/vinny/.cache/bower/packages/060a9fe0e60a0d3d6c9ed350cde03e61/1.5.6-build.4794%2Bsha.f1f892d'
    at Error (native)

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:109:18)
    at emitOne (events.js:90:13)
    at Logger.emit (events.js:182:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:808:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:752:41)

System info:
Bower version: 1.2.8
Node version: 5.6.0
OS: Darwin 15.3.0 x64
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33.816 s
[INFO] Finished at: 2016-05-11T15:50:41-04:00
[INFO] Final Memory: 30M/337M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.2:build (default) on project applicant-ux: Error during : bower install --no-color --allow-root: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

**Comment by trecloux** [comment]
What's happening if you directly launch bower from a command line ?
`bower install --no-color --allow-root`

**Comment by vinnysharma** [comment]
Wow, thanks for the quick reply. I get the same error when I launch bower directly from the command line. Error log below:

bower angular#^1.2.21                              ENOTEMPTY ENOTEMPTY: directory not empty, rmdir '/Users/vinny/.cache/bower/packages/060a9fe0e60a0d3d6c9ed350cde03e61/1.5.6-build.4794%2Bsha.f1f892d'

Stack trace:
Error: ENOTEMPTY: directory not empty, rmdir '/Users/vinny/.cache/bower/packages/060a9fe0e60a0d3d6c9ed350cde03e61/1.5.6-build.4794%2Bsha.f1f892d'
    at Error (native)

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:109:18)
    at emitOne (events.js:90:13)
    at Logger.emit (events.js:182:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:808:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:752:41)

System info:
Bower version: 1.2.8
Node version: 5.6.0
OS: Darwin 15.3.0 x64

**Comment by aillon** [comment]
Just a follow up on this thread and the reason why my build was failing.  It turned out that another developer was using the same file name for the ugligy/minify process.  By changing the name to a unique name, my issue (this build problem), went away.  Hope this helps somebody.
